all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become: yes

app_servers:
  hosts:
    app1:
      ansible_host: 212.111.84.154
      private_ip: 192.168.100.249
    app2:
      ansible_host: 212.111.86.216
      private_ip: 192.168.100.192

haproxy:
  hosts:
    haproxy-server:
      ansible_host: 212.111.84.45
      private_ip: 192.168.100.193

database:
  hosts:
    db:
      ansible_host: 212.111.86.216
