---
- name: Install required packages
  apt:
    name: [python3, python3-pip, python3-venv, git, mysql-client, virtualenv]
    state: present
  become: yes

- name: Remove existing application directory
  file:
    path: "{{ app_dir }}"
    state: absent
  become: yes
  ignore_errors: yes

- name: Clone Flask application
  git:
    repo: https://github.com/mmumshad/simple-webapp-flask.git
    dest: "{{ app_dir }}"
    version: master
  become: yes

- name: Install Python dependencies
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ app_dir }}/venv"
    virtualenv_command: python3 -m venv
  become: yes

- name: Create application configuration
  template:
    src: config.py.j2
    dest: "{{ app_dir }}/config.py"
  become: yes
  # Эта задача теперь автоматически использует переменные из vault

- name: Create systemd service
  template:
    src: flaskapp.service.j2
    dest: /etc/systemd/system/flaskapp.service
  become: yes
  notify: restart flaskapp

- name: Enable and start Flask app
  systemd:
    name: flaskapp
    enabled: yes
    state: started
  become: yes
